# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import planning_verification_pb2 as planning__verification__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in planning_verification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlanningVerificationServiceStub(object):
    """MoveIt 规划验证最小服务定义。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyPointToPoint = channel.unary_unary(
                '/robosdp.planning.v1.PlanningVerificationService/VerifyPointToPoint',
                request_serializer=planning__verification__pb2.PointToPointPlanningRequest.SerializeToString,
                response_deserializer=planning__verification__pb2.PointToPointPlanningResponse.FromString,
                _registered_method=True)


class PlanningVerificationServiceServicer(object):
    """MoveIt 规划验证最小服务定义。
    """

    def VerifyPointToPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlanningVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyPointToPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPointToPoint,
                    request_deserializer=planning__verification__pb2.PointToPointPlanningRequest.FromString,
                    response_serializer=planning__verification__pb2.PointToPointPlanningResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robosdp.planning.v1.PlanningVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robosdp.planning.v1.PlanningVerificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlanningVerificationService(object):
    """MoveIt 规划验证最小服务定义。
    """

    @staticmethod
    def VerifyPointToPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robosdp.planning.v1.PlanningVerificationService/VerifyPointToPoint',
            planning__verification__pb2.PointToPointPlanningRequest.SerializeToString,
            planning__verification__pb2.PointToPointPlanningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
