# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: planning_verification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'planning_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bplanning_verification.proto\x12\x13robosdp.planning.v1\"\xbd\x02\n\x1bPointToPointPlanningRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x19\n\x11planning_scene_id\x18\x02 \x01(\t\x12\x14\n\x0cmotion_group\x18\x03 \x01(\t\x12\x12\n\nplanner_id\x18\x04 \x01(\t\x12\x1f\n\x17\x61llowed_planning_time_s\x18\x05 \x01(\x01\x12\x1b\n\x13target_cycle_time_s\x18\x06 \x01(\x01\x12\x11\n\tjoint_ids\x18\x07 \x03(\t\x12\x1e\n\x16start_joint_values_deg\x18\x08 \x03(\x01\x12\x1d\n\x15goal_joint_values_deg\x18\t \x03(\x01\x12\x17\n\x0f\x63heck_collision\x18\n \x01(\x08\x12\x1c\n\x14\x63heck_self_collision\x18\x0b \x01(\x08\"I\n\x12TrajectoryWaypoint\x12\x19\n\x11time_from_start_s\x18\x01 \x01(\x01\x12\x18\n\x10joint_values_deg\x18\x02 \x03(\x01\"\xc7\x03\n\x1cPointToPointPlanningResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x19\n\x11transport_success\x18\x02 \x01(\x08\x12\x18\n\x10planning_success\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x12\n\nplanner_id\x18\x05 \x01(\t\x12\x17\n\x0fplanning_time_s\x18\x06 \x01(\x01\x12\x1d\n\x15trajectory_duration_s\x18\x07 \x01(\x01\x12:\n\twaypoints\x18\x08 \x03(\x0b\x32\'.robosdp.planning.v1.TrajectoryWaypoint\x12\x14\n\x0cin_collision\x18\t \x01(\x08\x12\x1b\n\x13\x63ollision_object_id\x18\n \x01(\t\x12\x19\n\x11\x63ollision_message\x18\x0b \x01(\t\x12\x19\n\x11in_self_collision\x18\x0c \x01(\x08\x12\x1d\n\x15self_collision_link_a\x18\r \x01(\t\x12\x1d\n\x15self_collision_link_b\x18\x0e \x01(\t\x12\x1e\n\x16self_collision_message\x18\x0f \x01(\t2\x98\x01\n\x1bPlanningVerificationService\x12y\n\x12VerifyPointToPoint\x12\x30.robosdp.planning.v1.PointToPointPlanningRequest\x1a\x31.robosdp.planning.v1.PointToPointPlanningResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planning_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINTTOPOINTPLANNINGREQUEST']._serialized_start=53
  _globals['_POINTTOPOINTPLANNINGREQUEST']._serialized_end=370
  _globals['_TRAJECTORYWAYPOINT']._serialized_start=372
  _globals['_TRAJECTORYWAYPOINT']._serialized_end=445
  _globals['_POINTTOPOINTPLANNINGRESPONSE']._serialized_start=448
  _globals['_POINTTOPOINTPLANNINGRESPONSE']._serialized_end=903
  _globals['_PLANNINGVERIFICATIONSERVICE']._serialized_start=906
  _globals['_PLANNINGVERIFICATIONSERVICE']._serialized_end=1058
# @@protoc_insertion_point(module_scope)
